##############################################
# Trivy Configuration
##############################################

format: table

exit-code: 1

severity:
  - CRITICAL
  - HIGH

ignore-unfixed: true

skip-dirs:
  - .terraform
  - .git
  - node_modules
  - vendor
  - dist
  - build

skip-files:
  - terraform.tfstate
  - terraform.tfstate.backup

scanners:
  - misconfig
  - secret

misconfiguration:
  include-non-failures: false

timeout: 10m

cache-dir: .trivycache