name: nivasabid

services:
  mysql:
    image: mysql:8.4

    container_name: mysql

    restart: unless-stopped

    env_file:
      - .env

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot123"]
      interval: 15s
      timeout: 5s
      retries: 10

    networks:
      - nivasabid-network

  backend:
    image: nivasabid-backend:2.0

    build:
      context: ../backend
      dockerfile: Dockerfile

    container_name: backend

    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    env_file:
      - .env

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}

      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${SERVER_PORT}

    ports:
      - "8080:8080"

    networks:
      - nivasabid-network

  frontend:
    image: nivasabid-frontend:2.0

    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_API_GOOGLE_KEY: ${VITE_API_GOOGLE_KEY}

    container_name: frontend

    restart: unless-stopped

    depends_on:
      backend:
        condition: service_started

    ports:
      - "5173:8080"

    networks:
      - nivasabid-network

volumes:
  mysql-data:

networks:
  nivasabid-network:
    driver: bridge
